class IssueTemplateAttribute < ApplicationRecord

  TYPE_GENERAL_DESCRIPTION = 0
  TYPE_TECHNICAL_DESCRIPTION = 1
  TYPE_UNORDERED_LIST = 2
  TYPE_ORDERED_LIST = 3
  TYPE_CODEBLOCK = 4

  ATTRIBUTE_TYPES = [ 0, 1, 2, 3, 4 ]

end
